language: python
python:
- '3.5'
- '3.6'
install:
- python setup.py install
- pip install -r docs/requirements.txt
- pip install coveralls
script:
- python setup.py test
- cd docs && make doctest && cd ..
after_success:
- coveralls
