version: "3"
services:
  repocribro:
    # locally built:
    # build: .
    # or public:
    image: mareksuchanek/repocribro:develop
    entrypoint: ["repocribro", "run", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      REPOCRIBRO_CONFIG_FILE: /repocribro/config.cfg
    volumes:
      - "./config/docker-config.example.cfg:/repocribro/config.cfg:ro"
    ports:
      - "5000:5000"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
