"""Privileges for role

Revision ID: 13a18cc60ee5
Revises: 891cf9712a20
Create Date: 2018-07-21 09:54:25.502179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a18cc60ee5'
down_revision = '891cf9712a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Role', sa.Column('privileges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Role', 'privileges')
    # ### end Alembic commands ###
