"""Repository secret must be unique

Revision ID: 2bcf4f4056e6
Revises: c111a746eec4
Create Date: 2017-01-27 19:29:30.735785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcf4f4056e6'
down_revision = 'c111a746eec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Repository', ['secret'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Repository', type_='unique')
    # ### end Alembic commands ###
