"""Fork as full_name

Revision ID: 416354ba65fb
Revises: 891cf9712a20
Create Date: 2018-07-19 15:06:00.341029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416354ba65fb'
down_revision = '891cf9712a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repository', sa.Column('parent_name', sa.String(length=150), nullable=True))
    op.drop_column('Repository', 'fork_of')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repository', sa.Column('fork_of', sa.INTEGER(), nullable=True))
    op.drop_column('Repository', 'parent_name')
    # ### end Alembic commands ###
