"""Adding URLs of GH objects

Revision ID: 5bf4f9988d35
Revises: edff7bbfe5cd
Create Date: 2017-01-24 14:16:48.123860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf4f9988d35'
down_revision = 'edff7bbfe5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Commit', sa.Column('url', sa.UnicodeText(), nullable=True))
    op.add_column('Push', sa.Column('compare_url', sa.UnicodeText(), nullable=True))
    op.add_column('Release', sa.Column('url', sa.UnicodeText(), nullable=True))
    op.add_column('Repository', sa.Column('url', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Repository', 'url')
    op.drop_column('Release', 'url')
    op.drop_column('Push', 'compare_url')
    op.drop_column('Commit', 'url')
    # ### end Alembic commands ###
