"""Add topics of Repository

Revision ID: 891cf9712a20
Revises: dc286086230c
Create Date: 2018-07-06 09:52:31.204206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891cf9712a20'
down_revision = 'dc286086230c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repository', sa.Column('topics', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Repository', 'topics')
    # ### end Alembic commands ###
