"""Webhook id for Repository

Revision ID: c111a746eec4
Revises: 2d9bf123d5b7
Create Date: 2017-01-26 19:21:06.401405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c111a746eec4'
down_revision = '2d9bf123d5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repository', sa.Column('webhook_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Repository', 'webhook_id')
    # ### end Alembic commands ###
