"""Init of Push, Commit and Release

Revision ID: edff7bbfe5cd
Revises: d397ce02489b
Create Date: 2017-01-22 18:50:53.473470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edff7bbfe5cd'
down_revision = 'd397ce02489b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Push',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('after', sa.Integer(), nullable=True),
    sa.Column('before', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('pusher_name', sa.UnicodeText(), nullable=True),
    sa.Column('pusher_email', sa.String(length=255), nullable=True),
    sa.Column('sender_login', sa.String(length=40), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('tag_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('prerelease', sa.Boolean(), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('body', sa.UnicodeText(), nullable=True),
    sa.Column('author_login', sa.String(length=40), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sender_login', sa.String(length=40), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['Repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=True),
    sa.Column('tree_sha', sa.String(length=40), nullable=True),
    sa.Column('message', sa.UnicodeText(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_name', sa.UnicodeText(), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('author_login', sa.String(length=40), nullable=True),
    sa.Column('committer_name', sa.UnicodeText(), nullable=True),
    sa.Column('committer_email', sa.String(length=255), nullable=True),
    sa.Column('committer_login', sa.String(length=40), nullable=True),
    sa.Column('push_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['push_id'], ['Push.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Commit')
    op.drop_table('Release')
    op.drop_table('Push')
    # ### end Alembic commands ###
